import { deriveObjects } from '../model/derive';
import type { HolderParams, Vec2 } from '../model/types';

// Generic OpenSCAD modules. Each object is emitted as an explicit point list so
// the .scad and the in-browser three.js geometry are identical by construction
// (the cross-check in scripts/verify-stl.ts relies on this). extrude_tube cuts
// a blind bore: the inner extrusion starts at `floor` and overshoots the top, so
// the hole is open at the top and closed `floor` mm above the base.
const MODULES = `module extrude_solid(pts, h) {
    linear_extrude(height = h) polygon(points = pts);
}

module extrude_tube(outer, inner, h, floor) {
    difference() {
        linear_extrude(height = h) polygon(points = outer);
        translate([0, 0, floor])
            linear_extrude(height = h) polygon(points = inner);
    }
}`;

/** Format a number for scad: integers stay bare, decimals trimmed to 4 places. */
function num(value: number): string {
  return Number.parseFloat(value.toFixed(4)).toString();
}

function points(pts: Vec2[]): string {
  return `[${pts.map(([x, y]) => `[${num(x)}, ${num(y)}]`).join(', ')}]`;
}

/** Generate an OpenSCAD source file for the holder. */
export function generateScad(params: HolderParams): string {
  const objects = deriveObjects(params);

  const body = objects
    .map((o) => {
      const place = `    translate([${num(o.centerX)}, ${num(o.centerY)}, base_height])`;
      if (o.inner === null) {
        return `    // object ${o.index + 1} — ${o.shape}, solid\n${place}\n        extrude_solid(${points(o.outer)}, ${num(o.height)});`;
      }
      return `    // object ${o.index + 1} — ${o.shape}, tube (blind)\n${place}\n        extrude_tube(${points(o.outer)}, ${points(o.inner)}, ${num(o.height)}, ${num(o.wallThickness)});`;
    })
    .join('\n\n');

  return `// Toothbrush holder — generated by Toothbrush Holder Generator.
// All dimensions in mm.

/* [Base plate] */
base_length = ${num(params.baseLength)};   // X
base_depth  = ${num(params.baseDepth)};    // Y
base_height = ${num(params.baseHeight)};    // Z (thickness)

/* [Rendering] */
$fn = ${num(params.fn)};            // facets per curve (higher = smoother, slower)

// Holes are always blind in this version (bores stop one wall above the base).
drain_through_base = false;

${MODULES}

module toothbrush_holder() {
    // base plate
    cube([base_length, base_depth, base_height]);

${body}
}

toothbrush_holder();
`;
}

export const SCAD_FILENAME = 'toothbrush-holder.scad';
