import { innerDiameter } from '../model/derive';
import type { HolderParams } from '../model/types';

// The model body is copied verbatim from the reference scad. It is already fully
// parametric over base_*, tubes, drain_through_base and $fn, so generation only
// substitutes the assignment block at the top.
const MODEL_BODY = `// ---- derived geometry ------------------------------------------------------

n      = len(tubes);
spacing = base_length / n;
y_center = base_depth / 2;

function tube_x(i) = spacing * (i + 0.5);

// ---- model -----------------------------------------------------------------

module toothbrush_holder() {
    difference() {
        union() {
            // base plate
            cube([base_length, base_depth, base_height]);

            // outer bodies of the tubes
            for (i = [0 : n - 1]) {
                od = tubes[i][0];
                h  = tubes[i][2];
                translate([tube_x(i), y_center, base_height])
                    cylinder(h = h, d = od);
            }
        }

        // inner bores
        for (i = [0 : n - 1]) {
            id = tubes[i][1];
            h  = tubes[i][2];
            z0 = drain_through_base ? -1 : base_height;
            // bore reaches the top of the tube; +1 keeps the top face open
            top = base_height + h + 1;
            translate([tube_x(i), y_center, z0])
                cylinder(h = top - z0, d = id);
        }
    }
}

toothbrush_holder();
`;

/** Format a number for scad output: integers stay bare, decimals are trimmed. */
function num(value: number): string {
  return Number.parseFloat(value.toFixed(4)).toString();
}

/** Generate an OpenSCAD source file matching the reference structure. */
export function generateScad(params: HolderParams): string {
  const rows = params.tubes
    .map((tube, i) => {
      const od = num(tube.outerDiameter);
      const id = num(innerDiameter(tube.outerDiameter, params.wallThickness));
      const h = num(tube.height);
      return `    [${od}, ${id}, ${h}],   // tube ${i + 1}`;
    })
    .join('\n');

  return `// Toothbrush holder — generated by Toothbrush Holder Maker.
// All dimensions in mm. Holes are blind (do not drain through the base).

/* [Base plate] */
base_length = ${num(params.baseLength)};   // X
base_depth  = ${num(params.baseDepth)};    // Y
base_height = ${num(params.baseHeight)};    // Z (thickness)

/* [Tubes] */
// One row per tube: [outer_diameter, inner_diameter, height]
// Order is left -> right. wall_thickness = ${num(params.wallThickness)} mm.
tubes = [
${rows}
];

// If true, the inner bore is cut all the way through the base so water
// can drain out the bottom. If false, the bore stops at the top of the
// base (a blind hole).
drain_through_base = false;

/* [Rendering] */
$fn = ${num(params.fn)};            // facets per circle (higher = smoother, slower)

${MODEL_BODY}`;
}

export const SCAD_FILENAME = 'toothbrush-holder.scad';
